[package]
name = "formal"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.40", features =["valuable"]}
itertools = "0.13.0"
thiserror = "1.0.63"

[dev-dependencies]
tracing-test = "0.2.5"
tracing-subscriber = "0.3.18"
tracing-assertions = "0.1.2"